### ISSUE TITLE
Error variable GARDER_X_VERSIONS not used

### ISSUE THREAD

**Issue by DavidBoB** [SebastienPi/sonatype-nexus-maven-release-clean-up#1]
Hi,

I found an error in the file at line 85.

You hard-coded 3 for the lines of the head-command:
head --lines -3

I think you must use the variable GARDER_X_VERSIONS  at this place like this:
head --lines -$GARDER_X_VERSIONS 

On my server I set the variable to 10 but the script keep anyway 3 Versions.

Thanks for the project.
Regards

**Comment by SebastienPi** [comment]
Thanks, fix in https://github.com/SebastienPi/sonatype-nexus-maven-release-clean-up/commit/25950b330be0fa9e64c6d4191d8f907742bccc49.
